=== intfrr/Towers/src/main/xsd/lineup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://lineup/util/config"
        xmlns:tns="http://lineup/util/config"
        elementFormDefault="qualified">


    <element name="mainConfig" type="tns:MainConfig"></element>
    
    <complexType name="MainConfig">
    	<sequence>
    		<element name="levels" type="tns:LevelList"></element>
    		<element name="creeps" type="tns:CreepList"></element>
    	</sequence>
    </complexType>

    <complexType name="CreepList">
    	<sequence>
    		<element name="creep" type="tns:CreepConfig" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="CreepConfig">
    	<sequence>
    		<element name="fqName" type="string" maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="ref" type="string"></attribute>
    </complexType>
    




    <complexType name="LevelList">
    	<sequence>
    		<element name="level" type="tns:LevelConfig" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="LevelConfig">
    	<sequence>
    		<element name="base" type="tns:Waypoint"></element>
    		<element name="route" type="tns:Route"></element>
    		<element name="background" type="string"></element>
    		<element name="waves" type="tns:WaveList"></element>
    	</sequence>
    	<attribute name="sequence" type="int"></attribute>
    </complexType>

    <complexType name="Waypoint">
    	<sequence>
    		<element name="x" type="int"></element>
    		<element name="y" type="int"></element>
    	</sequence>
    	<attribute name="sequence" type="int"></attribute>
    </complexType>

    <complexType name="Route">
    	<sequence>
    		<element name="waypoint" type="tns:Waypoint" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="WaveConfig">
    	<sequence>
    		<element name="creepRef" type="string"></element>
    		<element name="interval" type="double"></element>
    		<element name="count" type="int"></element>
    	</sequence>
    	<attribute name="sequence" type="int"></attribute>
    </complexType>

    <complexType name="WaveList">
    	<sequence>
    		<element name="wave" type="tns:WaveConfig" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== intfrr/Towers/src/main/resources/mainConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:mainConfig xmlns:tns="http://lineup/util/config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://lineup/util/config ../xsd/lineup.xsd ">
	
	<tns:levels>
		<tns:level sequence="1">
			<tns:base sequence="0">
				<tns:x>102</tns:x>
				<tns:y>118</tns:y>
			</tns:base>
			<tns:route>
				<tns:waypoint sequence="1">
					<tns:x>9</tns:x>
					<tns:y>176</tns:y>
				</tns:waypoint>
				<tns:waypoint sequence="2">
					<tns:x>175</tns:x>
					<tns:y>141</tns:y>
				</tns:waypoint>
				<tns:waypoint sequence="3">
					<tns:x>133</tns:x>
					<tns:y>29</tns:y>
				</tns:waypoint>
				<tns:waypoint sequence="4">
					<tns:x>35</tns:x>
					<tns:y>57</tns:y>
				</tns:waypoint>
			</tns:route>
			<tns:background>lvl1.jpg</tns:background>
			<tns:waves>
				<tns:wave sequence="1">
					<tns:creepRef>blue</tns:creepRef>
					<tns:interval>12</tns:interval>
					<tns:count>1</tns:count>
				</tns:wave>
				<tns:wave sequence="2">
					<tns:creepRef>red</tns:creepRef>
					<tns:interval>12</tns:interval>
					<tns:count>8</tns:count>
				</tns:wave>
			</tns:waves>
		</tns:level>
	</tns:levels>
	
	<tns:creeps>
		<tns:creep ref="blue">
			<tns:fqName>lineup.model.implementations.creeps.BlueCreep</tns:fqName>
		</tns:creep>
		<tns:creep ref="red">
			<tns:fqName>lineup.model.implementations.creeps.RedCreep</tns:fqName>
		</tns:creep>
	</tns:creeps>
	
</tns:mainConfig>
